language: ruby
sudo: false
rvm:
  - 2.7
  - 2.6
  - 2.5
env:
  - RAILS_VERSION="~> 5.1.0"
  - RAILS_VERSION="~> 5.2.0"
  - RAILS_VERSION="~> 6.0.0"
  - RAILS_VERSION="~> 6.1.0"
  - RAILS_VERSION="master"
before_script:
  - "cd spec/dummy; rake db:migrate; rake db:test:prepare; cd ../.."
after_script:
  - "cat coverage/coverage.txt"
notifications:
  email: false
