name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [5.1.0, 5.2.0, 6.0.0, 6.1.0, master]
        ruby_version: [3.0, 2.7, 2.6, 2.5]
        exclude:
          - ruby_version: 2.5
            rails_version: master
          - ruby_version: 2.6
            rails_version: master
          - ruby_version: 3.0
            rails_version: 5.1.0
          - ruby_version: 3.0
            rails_version: 5.2.0

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}

    - name: Run test
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
      run: |
        bundle update
        cd spec/dummy; rake db:migrate db:test:prepare; cd ../..
        bundle exec rake

    - name: Upload coverage
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: coverage-ruby-${{ matrix.ruby_version }}-rails-${{ matrix.rails_version }}
        path: coverage

    - name: Show coverage
      if: always()
      run: |
        cat coverage/coverage.txt
